#
name: Test CI java 11 - angular 14 - 003

on:
  push:
    branches: [ "franck-g75-TestCI-java11-angular14" ]
  pull_request:
    branches: [ "franck-g75-TestCI-java11-angular14" ]

#jobs:

#  -----------------------Back End JAVA ----------------------------
#  backend:
  
#    build:
#      name: Backend
#      runs-on: ubuntu-latest
#      defaults:
#        run:
#          working-directory: back

#      steps:
#      - name: Checkout
#        uses: actions/checkout@v6

#      - name: Setup Java 11
#        uses: actions/setup-java@v4
#        with:
#          distribution: temurin
#          java-version: '11'
#          cache: maven

#      - name: Maven tests 
#        run: mvn --batch-mode clean verify 

#-----------------------Front End JAVA ---------------------------- 
#  frontend: 
    #name: Frontend
build:

  runs-on: ubuntu-latest
  defaults:
    run:
      working-directory: front
  strategy:
    matrix:
      node-version: [14.21.x]
      # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

  steps:
  - uses: actions/checkout@v4
  - name: Use Node.js ${{ matrix.node-version }}
    uses: actions/setup-node@v4
    with:
      node-version: ${{ matrix.node-version }}
      cache: 'npm'
      cache-dependency-path: front/package-lock.json
  - run: npm ci
  - run: npm run build --if-present
  - run: npm ci

