#building and testing angular14
name: Test CI - angular 14 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: front
    strategy:
      matrix:
        node-version: [14.21.x]
        #  See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: front/package-lock.json
    
    #installation des dépendances
    - run: npm ci
    #build de la solution
    - run: npm run build --if-present
    #lancer les tests prédéfinis
    - run: npm run test-ci